### ISSUE TITLE
License

### ISSUE THREAD

**Issue by M-RBDR** [electronstudio/python_book#1]
Will the third edition still be licensed under a Creative Commons Attribution-ShareAlike license? I would be interested in translating your book to french for a school computer club.

**Comment by electronstudio** [comment]
I haven’t decided yet. The third edition might turn out to be quite different and will probably take me a while to finish before it’s ready to be translated yet anyway. So probably best to translate the second edition if you want something now. 

So far in this repo I’ve just been converting the second edition to use RestructuredText instead of Markdown. I can certainly release that under CC, so if you prefer to work with RestructuredText I can release a RestructuredText Second Edition for you.

**Comment by M-RBDR** [comment]
That would be great since softcover is a bit finicky on Linux with how it deals with fonts. I also want to take this opportunity to thank you for the work you did on the second edition. It is a wonderful resource to start up a club/dojo quickly for teachers that are in need of a basic template.

**Comment by electronstudio** [comment]
Thanks.

I have put up a "2.1 edition" in a new branch here https://github.com/electronstudio/pygame-zero-book/ still licensed under CC.  Suggest this version for translating.
